#### welcome to numpy tutorial

In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,32,7]], np.int32)

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
 myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 32,  7]])

**Array creation: Creaton from other Python structures**

In [10]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,2]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 2]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,23,12})

array({34, 12, 23}, dtype=object)

In [16]:
zer = np.zeros((2,5))

In [17]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,10,5)
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
       [8.45593934e-307, 9.34600963e-307, 7.56601165e-307,
        1.69118787e-306, 1.60220393e-306, 1.37961302e-306],
       [1.78021798e-306, 1.37961709e-306, 6.89805151e-307,
        7.56592338e-307, 6.89807188e-307, 2.22522597e-306],
       [1.24610791e-306, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 1.42410974e-306, 8.45528067e-307]])

In [21]:
ep_like = np.empty_like(lspace)
ep_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
ide = np.identity(32)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(32, 32)

In [24]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
p = arr.reshape(3,33)
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
p.size

99

In [27]:
q = p.ravel()
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
q.shape

(99,)

In [59]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [63]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
ar.sum(axis = 0)

array([ 6, 15,  8])

In [69]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [71]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [73]:
ar.flat

In [83]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [85]:
ar.ndim

2

In [87]:
ar.size

9

In [89]:
ar.nbytes

36

In [93]:
one = np.array([1,3,4,657,2])

In [95]:
one.argmax()

3

In [97]:
one.argmin()

0

In [99]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [101]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

## gives index of minimum element

In [111]:
ar.argmin()  

8

In [105]:
ar.argmax()

6

In [113]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [115]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [117]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [119]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [123]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [125]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [127]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [129]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [131]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [133]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [135]:
ar.sum()

29

In [137]:
ar.max()

7

In [144]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [146]:
type(np.where(ar>5))

tuple

In [148]:
np.count_nonzero(ar)

8

In [150]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [152]:
ar[1,2] = 0

In [154]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [156]:
import sys

In [158]:
py_ar = [0,4,55,2]

In [160]:
np_ar = np.array(py_ar)

In [162]:
sys.getsizeof(1)*len(py_ar)

112

In [168]:
np_ar.itemsize*np_ar.size

16

In [170]:
np_ar.tolist()

[0, 4, 55, 2]